# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_model.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10\x64\x61ta_model.proto"\x8f\x03\n\tDataModel\x12\x12\n\nsession_id\x18\x01 \x01(\x03\x12\x0c\n\x04mpid\x18\x02 \x01(\x03\x12\x1a\n\x12session_start_time\x18\x03 \x01(\t\x12\x18\n\x10session_end_time\x18\x04 \x01(\t\x12\x18\n\x10session_duration\x18\x05 \x01(\x03\x12\n\n\x02ip\x18\x06 \x01(\t\x12\x14\n\x0c\x63ountry_iso2\x18\x07 \x01(\t\x12\x12\n\nstore_code\x18\x08 \x01(\t\x12\x13\n\x0b\x64ispatch_id\x18\t \x01(\t\x12\x12\n\nvariant_id\x18\n \x01(\t\x12\x14\n\x0cutm_campaign\x18\x0b \x01(\t\x12\x12\n\nutm_medium\x18\x0c \x01(\t\x12\x12\n\nutm_source\x18\r \x01(\t\x12\x19\n\x11\x61\x63tivity_platform\x18\x0e \x01(\t\x12\x18\n\x10operating_system\x18\x0f \x01(\t\x12\x13\n\x0bupdate_date\x18\x10 \x01(\t\x12\x13\n\x0bupdate_user\x18\x11 \x01(\t\x12\x14\n\x0c_CHANGE_TYPE\x18\x12 \x01(\t'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "data_model_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_DATAMODEL"]._serialized_start = 21
    _globals["_DATAMODEL"]._serialized_end = 420
# @@protoc_insertion_point(module_scope)
